### ISSUE TITLE
Wrong database relationship

### ISSUE THREAD

**Issue by LuTrongTuan** [m1nh101/PearPhone2022#1]
Database đang sai mỗi quan hệ bảng stock và phone

**Comment by m1nh101** [comment]
No bug found!

**Comment by LuTrongTuan** [comment]
Sai quan hệ giữa bản stock và phone

**Comment by m1nh101** [comment]
fixed. Please check at [https://github.com/m1nh101/PearPhone2022/commit/1964bb328e1f44352bb7fe1788080564c2725d27](url)
